services:
  - type: web
    name: staticfund-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
